Add Expo guide
criipto/docs pull request #78
Opened 2023-07-24 13:33 UTC by nmoskaleva

2023-07-24 13:37 UTC, mickhansen requested changes

2023-07-24 13:37 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +## Local development
This section doesn't make sense in a implementation guide.

2023-07-24 13:37 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +## App switch support
This section should be rewritten to be more focused on being an implementation guide I think.
The `supports` statement doesn't matter in a guide I think, but we can move the `Danish MitID + Android` to later in the guide, after installation/implementation.

2023-07-24 13:38 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +title: React Native | Expo
`Expo (React Native)` might make a little more sense.

2023-07-24 13:38 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +sort: 0
Double check the sort please.

2023-07-24 13:39 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +sort: 0
Guess most of the guides have `sort: 0`?

2023-07-25 08:49 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +For example, if you are running your application locally, the callback URL could be `http://localhost:19006/`. Alternatively, if developing in Expo Go, the callback URL may look like this: `exp://127
It will never be a `http://` url when developing a mobile application (and we don't support Expo web)

2023-07-25 08:49 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +For example, if you are running your application locally, the callback URL could be `http://localhost:19006/`. Alternatively, if developing in Expo Go, the callback URL may look like this: `exp://127
Might want to provide examples using custom schemes instead,

2023-07-25 08:50 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +</Highlight>
Link to expo guide on universal links

2023-07-25 08:51 UTC, nmoskaleva commented on src/pages/verify/integrations/react-native-expo.mdx
> +Here, you have an option to pass [`acr_values`](/verify/guides/authorize-url-builder/#auth-methods--acr-values) for the eIDs you want to use in your code. Alternatively, you can configure the relevan
Good to know!

2023-07-25 08:52 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +Here, you have an option to pass [`acr_values`](/verify/guides/authorize-url-builder/#auth-methods--acr-values) for the eIDs you want to use in your code. Alternatively, you can configure the relevan
Also the `login` method does not support not passing a acr value, and the `login` method is the critical piece of the integration.

2023-07-26 07:46 UTC, mickhansen approved these changes

2023-07-26 07:47 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +For example, if you are developing your application in Expo Go, the callback URL may look like this: `exp://127.0.0.1:8081`.
Expand this sentence with "or if you've setup a custom scheme, it might look like `yourscheme://auth/callback`"

2023-07-26 07:48 UTC, mickhansen commented on src/pages/verify/integrations/react-native-expo.mdx
> +      const redirectUri = Linking.createURL('/auth/criipto');
change `/auth/criipto` to `/auth/callback` I think.

2023-07-26 08:10 UTC, merged